sudo: false
language: android
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-24.0.0
    - android-24

script: cd Clover && ./gradlew build --console plain -x lint
